name: buss1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-322.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.8
  google_maps_flutter_web: ^0.5.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
